### ISSUE TITLE
Not possible to change linear advance, extruder stops extruding

### ISSUE THREAD

**Issue by DKXAM** [nehilo/KP3S#12]
Hey, thanks for the great FW

As far as i have seen it is not possible to change linear advance settings, the extruder stops extruding on the next layer. Is this a bug?

Greetings

**Comment by nehilo** [comment]
> Hey, thanks for the great FW
> 
> 
> 
> As far as i have seen it is not possible to change linear advance settings, the extruder stops extruding on the next layer. Is this a bug?
> 
> 
> 
> Greetings

You need to change driver on TMC2209

**Comment by DKXAM** [comment]
Ah okay, would be good to mention that in the description that you should not change linear advance with the default stepper drivers as it makes prints fail.
Thanks for the awnser and FW
