### ISSUE TITLE
Cant extrude manually via pronterface or lcd touch

### ISSUE THREAD

**Issue by EA2OY** [nehilo/kp3s#3]
Dear Nehilo, 

The firmware is near perfect, i have a bug, i cant extrude manually, maybe its limited in marlin? thanks in advance, i need to do this to calibrate e-step.

And, is possible to rotate  lcd 180 degrees? its made me easier to manage this because o dont want to print the adapter to re-orient lcd screen.

**Comment by nehilo** [comment]
> Dear Nehilo, 
> 
> 
> 
> The firmware is near perfect, i have a bug, i cant extrude manually, maybe its limited in marlin? thanks in advance, i need to do this to calibrate e-step.
> 
> 
> 
> And, is possible to rotate  lcd 180 degrees? its made me easier to manage this because o dont want to print the adapter to re-orient lcd screen.

This is marlin extruder protection. You need to read marlin documentation an cut-off it from repieter host via gcode command.

This is not possible to rotate tft because library on tft24 not support it. Revers mechanical lcd
