### ISSUE TITLE
Sources or config files

### ISSUE THREAD

**Issue by KiZDGGit** [nehilo/KP3S#4]
Hello! Great job!

I need the source files, or at least both config files to config language and steps por BMG (400 steps is not easy!). 

Thanks in advance.

**Comment by crypt1ct3ch** [comment]
nehilo does not share the source files, check closed issues. It has been asked for a few times.

**Comment by KiZDGGit** [comment]
OK, I don't like, and should share (Marlin license...), but it's ok. Great work anyway.
